# Generated by Django 5.1.6 on 2025-11-29 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekte'},
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.CharField(blank=True, help_text='Nur bei öffentlichen Projekten, z. B. GitHub Pages Link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inviteduser',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, help_text="z. B. https://github.com/... oder 'privat – auf Anfrage'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public_demo',
            field=models.BooleanField(default=False, verbose_name='Öffentlich sichtbar?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=300, verbose_name='Technologien'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional – kannst du später hochladen', null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
