# Generated by Django 5.1.6 on 2025-12-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_live_demo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_demo_url',
            field=models.CharField(blank=True, help_text='Nur bei öffentlichen Projekten', max_length=500, null=True),
        ),
    ]
