# Generated by Django 5.1.6 on 2025-12-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="z.B. 'Guest Icon-Challenge Modal'", max_length=200, verbose_name='Titel')),
                ('image', models.ImageField(upload_to='portfolio/screenshots/', verbose_name='Screenshot')),
                ('description', models.TextField(blank=True, help_text='Erkläre, was auf dem Screenshot zu sehen ist', verbose_name='Beschreibung')),
                ('section', models.CharField(choices=[('overview', '🎯 Projekt-Übersicht'), ('architecture', '🏗️ System-Architektur'), ('auth', '🔐 Auth-System'), ('deployment', '🚀 Deployment'), ('challenges', '💡 Technical Challenges'), ('apis', '🔌 API-Integrationen')], default='overview', max_length=100, verbose_name='Sektion')),
                ('order', models.IntegerField(default=0, help_text='Niedrigere Zahlen = weiter oben', verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio-Screenshot',
                'verbose_name_plural': 'Portfolio-Screenshots',
                'ordering': ['section', 'order', '-created_at'],
            },
        ),
    ]
