# Generated by Django 5.1.6 on 2026-01-01 11:14

import cloudinary.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_portfolioscreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoredTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('cyan', 'Cyan'), ('gray', 'Gray')], default='gray', help_text='Tailwind color für diesen Tag', max_length=20)),
            ],
            options={
                'verbose_name': 'Tech Tag',
                'verbose_name_plural': 'Tech Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaggedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='core.coloredtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurze, prägnante Headline', max_length=200)),
                ('description', models.TextField(help_text='Vollständige Beschreibung (Markdown supported)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True, help_text='Gehört zu aktuellem Projekt?')),
                ('update_type', models.CharField(choices=[('milestone', '🎯 Milestone'), ('daily', '🔧 Daily Update'), ('feature', '✨ New Feature'), ('bugfix', '🐛 Bug Fix'), ('note', '📝 Note')], default='daily', help_text='Art des Updates', max_length=20)),
                ('code_snippet', models.TextField(blank=True, help_text='Code-Snippet (optional)')),
                ('screenshot', cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot (optional)', max_length=255, null=True, verbose_name='image')),
                ('github_link', models.URLField(blank=True, help_text='Link zu GitHub Commit/PR (optional)')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags komma-getrennt eingeben (Auto-Complete!)', through='core.TaggedUpdate', to='core.ColoredTag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
